In [4]:
# pip install scikit-learn
import pandas as pd
import numpy as np

In [5]:
# load the data
df = pd.read_csv("heart.csv")

In [6]:
# Check value counts for Sex before modifying 
df['Sex'].value_counts()

Sex
M    725
F    193
Name: count, dtype: int64

In [7]:
# mapping the Sex variable into binary format (0 and 1)
# Gender 

target_mapping = {
    "M": 1, 
    "F": 0
}

df["Sex"] = df["Sex"].map(target_mapping)
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,0,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,1,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,0,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,1,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [8]:
# Check value counts for ChestPainType before modifying 
df['ChestPainType'].value_counts()

ChestPainType
ASY    496
NAP    203
ATA    173
TA      46
Name: count, dtype: int64

In [9]:
# Check value counts for RestingECG before modifying 
df['RestingECG'].value_counts()

RestingECG
Normal    552
LVH       188
ST        178
Name: count, dtype: int64

In [10]:
# this makes multiple columns with the variable (Separate for yes/no)
from sklearn.preprocessing import OneHotEncoder
variables = ['ChestPainType', 'RestingECG']

# use encoder
encoder = OneHotEncoder(sparse_output=False).set_output(transform="pandas")
one_hot_encoded = encoder.fit_transform(df[variables]).astype(int)
df = pd.concat([df,one_hot_encoded],axis=1).drop(columns=variables)

df.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST
0,40,1,140,289,0,172,N,0.0,Up,0,0,1,0,0,0,1,0
1,49,0,160,180,0,156,N,1.0,Flat,1,0,0,1,0,0,1,0
2,37,1,130,283,0,98,N,0.0,Up,0,0,1,0,0,0,0,1
3,48,0,138,214,0,108,Y,1.5,Flat,1,1,0,0,0,0,1,0
4,54,1,150,195,0,122,N,0.0,Up,0,0,0,1,0,0,1,0

In [11]:
# Check value counts for ST_Slope before modifying 
df['ST_Slope'].value_counts()

ST_Slope
Flat    460
Up      395
Down     63
Name: count, dtype: int64

In [12]:
cut_mapper = {'Down': 1, 'Flat': 2,'Up': 3}
df['ST_Slope'] = df['ST_Slope'].map(cut_mapper)
df.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST
0,40,1,140,289,0,172,N,0.0,3,0,0,1,0,0,0,1,0
1,49,0,160,180,0,156,N,1.0,2,1,0,0,1,0,0,1,0
2,37,1,130,283,0,98,N,0.0,3,0,0,1,0,0,0,0,1
3,48,0,138,214,0,108,Y,1.5,2,1,1,0,0,0,0,1,0
4,54,1,150,195,0,122,N,0.0,3,0,0,0,1,0,0,1,0

In [13]:
# Check value counts for ExerciseAngina before modifying 
df['ExerciseAngina'].value_counts()

ExerciseAngina
N    547
Y    371
Name: count, dtype: int64

In [14]:
# this just converts the value of column to 0 or 1
# factorize in pandas works too, but only one column at a time
from sklearn.preprocessing import LabelEncoder
variables = ['ExerciseAngina']
encoder = LabelEncoder()
df[variables] = df[variables].apply(encoder.fit_transform)

df.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST
0,40,1,140,289,0,172,0,0.0,3,0,0,1,0,0,0,1,0
1,49,0,160,180,0,156,0,1.0,2,1,0,0,1,0,0,1,0
2,37,1,130,283,0,98,0,0.0,3,0,0,1,0,0,0,0,1
3,48,0,138,214,0,108,1,1.5,2,1,1,0,0,0,0,1,0
4,54,1,150,195,0,122,0,0.0,3,0,0,0,1,0,0,1,0

In [15]:
# Save the cleaned dataset to a new CSV file
df.to_csv("HeartDisease_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!