#### RFE and Mutual Information to choose optimal variable for the dataset (and study potentially redundant ones)

In [8]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import RFE, mutual_info_regression, mutual_info_classif
from sklearn.model_selection import train_test_split
import seaborn as sns

# load data
df = pd.read_csv("../laptop_data_cleaned.csv")

# handle these better with your own dataset, here we are simply dropping these
#df = df.drop(['id', 'date', 'zipcode', 'lat', 'long'], axis=1)

# change this to your own target variable
TARGET_VARIABLE = "Price"

##### RFE - recursive feature elimination

In [9]:
# converts nominal variables into binary 

from sklearn.preprocessing import OneHotEncoder
variables = ['Company','TypeName','Cpu_brand','Gpu_brand','Os']
# use encoder
encoder = OneHotEncoder(sparse_output=False).set_output(transform="pandas")
one_hot_encoded = encoder.fit_transform(df[variables]).astype(int)
df = pd.concat([df,one_hot_encoded],axis=1).drop(columns=variables)
df.head()

,Ram,Weight,Price,TouchScreen,Ips,Ppi,HDD,SSD,Company_Acer,Company_Apple,...,Cpu_brand_Intel Core i3,Cpu_brand_Intel Core i5,Cpu_brand_Intel Core i7,Cpu_brand_Other Intel Processor,Gpu_brand_AMD,Gpu_brand_Intel,Gpu_brand_Nvidia,Os_Mac,Os_Others,Os_Windows
0,8,1.37,11.175755,0,1,226.983005,0,128,0,1,...,0,1,0,0,0,1,0,1,0,0
1,8,1.34,10.776777,0,0,127.677940,0,0,0,1,...,0,1,0,0,0,1,0,1,0,0
2,8,1.86,10.329931,0,0,141.211998,0,256,0,0,...,0,1,0,0,0,1,0,0,1,0
3,16,1.83,11.814476,0,1,220.534624,0,512,0,1,...,0,0,1,0,1,0,0,1,0,0
4,8,1.37,11.473101,0,1,226.983005,0,256,0,1,...,0,1,0,0,0,1,0,1,0,0

In [10]:
# typical X/y -split
X = df.drop(TARGET_VARIABLE, axis=1)
y = df[TARGET_VARIABLE]

# define model (linear regression, random forest, XGBoost etc.)
# technically you can use pretty much any classic ML algorithm
# model = LinearRegression()

# idea: you might want to try RFE with multuple ML algorithms
# and then cross-validate the results (which results are common in all models)

# another idea: if you plan on using e.g. XGBoost in your final model
# it's probably a good idea to use the same XGBoost here
model = RandomForestRegressor()

# create RFE, place the model and choose number of optimal variables
rfe = RFE(estimator=model, n_features_to_select=7)

# fit the RFE model with our data
rfe.fit(X, y)

# get rankings and results
rankings = rfe.ranking_
support = rfe.support_

# build a DataFrame to wrap up result for easier inspection
results_df = pd.DataFrame({
    "Feature": X.columns,
    "Ranking": rankings,
    "Selected": support
}).sort_values(by="Ranking")

# you can use these results with any other knowledge you have
# from other optimal variable selection tools, and cross-validation
results_df

                            Feature  Ranking  Selected
0                               Ram        1      True
1                            Weight        1      True
6                               SSD        1      True
4                               Ppi        1      True
29                TypeName_Notebook        1      True
34          Cpu_brand_Intel Core i5        1      True
36  Cpu_brand_Other Intel Processor        1      True
41                        Os_Others        2     False
35          Cpu_brand_Intel Core i7        3     False
31             TypeName_Workstation        4     False
3                               Ips        5     False
14                       Company_HP        6     False
5                               HDD        7     False
17                   Company_Lenovo        8     False
37                    Gpu_brand_AMD        9     False
2                       TouchScreen       10     False
42                       Os_Windows       11     False
11                     Company_Dell       12     False
38                  Gpu_brand_Intel       13     False
9                      Company_Asus       14     False
33          Cpu_brand_Intel Core i3       15     False
7                      Company_Acer       16     False
32          Cpu_brand_AMD Processor       17     False
39                 Gpu_brand_Nvidia       18     False
30               TypeName_Ultrabook       19     False
21                    Company_Razer       20     False
26      TypeName_2 in 1 Convertible       21     False
27                  TypeName_Gaming       22     False
23                  Company_Toshiba       23     False
28                 TypeName_Netbook       24     False
24                     Company_Vero       25     False
18                      Company_MSI       26     False
20                Company_Microsoft       27     False
10                    Company_Chuwi       28     False
25                   Company_Xiaomi       29     False
22                  Company_Samsung       30     False
40                           Os_Mac       31     False
19                 Company_Mediacom       32     False
12                  Company_Fujitsu       33     False
8                     Company_Apple       34     False
16                       Company_LG       35     False
15                   Company_Huawei       36     False
13                   Company_Google       37     False

In [11]:
# the selection loosely follow the correlations it seems
# this might imply the data is more or less linear or something else
df.corr()[TARGET_VARIABLE].sort_values(ascending=False)

Price                              1.000000
Ram                                0.680519
SSD                                0.658808
Cpu_brand_Intel Core i7            0.593245
Ppi                                0.480687
TypeName_Gaming                    0.362537
Gpu_brand_Nvidia                   0.357157
TypeName_Ultrabook                 0.306406
Os_Windows                         0.294626
Ips                                0.279240
TypeName_Workstation               0.206745
TouchScreen                        0.194289
Company_MSI                        0.188654
Weight                             0.151386
Company_Razer                      0.133549
TypeName_2 in 1 Convertible        0.093719
Company_Apple                      0.093356
Os_Mac                             0.093356
Company_Dell                       0.084610
Company_Toshiba                    0.069182
Company_LG                         0.062273
Company_Microsoft                  0.052978
Company_Samsung                    0.044365
Company_Google                     0.042908
Company_Huawei                     0.026080
Company_Xiaomi                     0.015207
Cpu_brand_Intel Core i5            0.005343
Company_Asus                      -0.018449
Company_HP                        -0.019252
Company_Fujitsu                   -0.020767
Company_Lenovo                    -0.042994
Company_Chuwi                     -0.089796
HDD                               -0.097361
Company_Vero                      -0.133899
Company_Mediacom                  -0.142000
TypeName_Netbook                  -0.146852
Gpu_brand_Intel                   -0.192402
Gpu_brand_AMD                     -0.202803
Cpu_brand_AMD Processor           -0.230121
Company_Acer                      -0.249514
Cpu_brand_Intel Core i3           -0.324742
Os_Others                         -0.348033
Cpu_brand_Other Intel Processor   -0.462839
TypeName_Notebook                 -0.566663
Name: Price, dtype: float64

#### Mutual information - another alternative

In [12]:
# fit the mutual information algorithm
# => that's why either or works
mi = mutual_info_regression(X, y)

# convert results into DataFrame
mi_results = pd.Series(mi, index=X.columns).sort_values(ascending=False)

# high value => variable is strongly connected to target variable
# low value => weak connection
# e.g. very similar to phik-matrix
mi_results

Ram                                0.497629
Ppi                                0.408574
SSD                                0.359718
Weight                             0.289781
TypeName_Notebook                  0.226078
Cpu_brand_Intel Core i7            0.222843
Cpu_brand_Other Intel Processor    0.152184
Cpu_brand_Intel Core i3            0.129109
Cpu_brand_Intel Core i5            0.123598
Gpu_brand_Nvidia                   0.089540
TypeName_Ultrabook                 0.074968
TypeName_Gaming                    0.074915
HDD                                0.071423
Os_Others                          0.071284
Os_Windows                         0.057545
Company_Acer                       0.046071
Gpu_brand_Intel                    0.038741
Ips                                0.033113
Cpu_brand_AMD Processor            0.030976
TouchScreen                        0.027416
TypeName_Workstation               0.027401
Gpu_brand_AMD                      0.025203
Company_MSI                        0.023442
TypeName_Netbook                   0.019774
Company_Lenovo                     0.014042
Company_Mediacom                   0.013478
TypeName_2 in 1 Convertible        0.012346
Company_Toshiba                    0.009828
Company_Vero                       0.009576
Company_Razer                      0.008890
Company_Samsung                    0.008213
Os_Mac                             0.007874
Company_Apple                      0.006448
Company_Asus                       0.004009
Company_Dell                       0.001939
Company_Chuwi                      0.001788
Company_Xiaomi                     0.001555
Company_Huawei                     0.001284
Company_Google                     0.001101
Company_Microsoft                  0.000012
Company_HP                         0.000000
Company_LG                         0.000000
Company_Fujitsu                    0.000000
dtype: float64