#### Phik-matrix -> Associations
Associations measure the strength of assocation between two variables. While correlations only measure LINEAR connection, associations can also handle non-linear connections. See "associations_vs_correlations.ipynb" for a simple comparison where associations are usually more useful.

NOTE! You can see both the correlations and associations at the asme time if you use SweetViz or Dython! You can also have correlations/phik-matrix in ydata at the same time, if you configure it correctly.

In [1]:
# if phik-matrix not found in pandas, try:
# pip install phik
import phik
import pandas as pd

# load data
df = pd.read_csv("../laptop_data_cleaned.csv")
# compute phik-matrix values
phik_matrix = df.phik_matrix()

phik_matrix

interval columns not set, guessing: ['Ram', 'Weight', 'Price', 'TouchScreen', 'Ips', 'Ppi', 'HDD', 'SSD']

,Company,TypeName,Ram,Weight,Price,TouchScreen,Ips,Ppi,Cpu_brand,HDD,SSD,Gpu_brand,Os
Company,1.000000,0.576621,0.293465,0.520811,0.545308,0.304272,0.372112,0.682741,0.433755,0.387587,0.318880,0.507095,0.870695
TypeName,0.576621,1.000000,0.543819,0.650047,0.546738,0.935956,0.426996,0.581258,0.415241,0.506266,0.545572,0.821429,0.518826
Ram,0.293465,0.543819,1.000000,0.520624,0.603574,0.122702,0.184651,0.376357,0.365249,0.210071,0.636930,0.541629,0.182614
Weight,0.520811,0.650047,0.520624,1.000000,0.646614,0.464916,0.381492,0.726083,0.475729,0.551385,0.305005,0.631244,0.337564
Price,0.545308,0.546738,0.603574,0.646614,1.000000,0.298160,0.361980,0.694533,0.847642,0.316863,0.599405,0.438146,0.385380
TouchScreen,0.304272,0.935956,0.122702,0.464916,0.298160,1.000000,0.205249,0.613899,0.108739,0.364895,0.359879,0.156023,0.053078
Ips,0.372112,0.426996,0.184651,0.381492,0.361980,0.205249,1.000000,0.484996,0.165786,0.267223,0.319201,0.100219,0.102306
Ppi,0.682741,0.581258,0.376357,0.726083,0.694533,0.613899,0.484996,1.000000,0.557045,0.529210,0.515965,0.547465,0.603920
Cpu_brand,0.433755,0.415241,0.365249,0.475729,0.847642,0.108739,0.165786,0.557045,1.000000,0.223734,0.405483,0.560094,0.238448
HDD,0.387587,0.506266,0.210071,0.551385,0.316863,0.364895,0.267223,0.529210,0.223734,1.000000,0.539660,0.359151,0.100155
SSD,0.318880,0.545572,0.636930,0.305005,0.599405,0.359879,0.319201,0.515965,0.405483,0.539660,1.000000,0.335583,0.411131
Gpu_brand,0.507095,0.821429,0.541629,0.631244,0.438146,0.156023,0.100219,0.547465,0.560094,0.359151,0.335583,1.000000,0.195480
Os,0.870695,0.518826,0.182614,0.337564,0.385380,0.053078,0.102306,0.603920,0.238448,0.100155,0.411131,0.195480,1.000000

In [3]:
phik_matrix['Price'].sort_values(ascending=False)

Price          1.000000
Cpu_brand      0.847642
Ppi            0.694533
Weight         0.646614
Ram            0.603574
SSD            0.599405
TypeName       0.546738
Company        0.545308
Gpu_brand      0.438146
Os             0.385380
Ips            0.361980
HDD            0.316863
TouchScreen    0.298160
Name: Price, dtype: float64

In [4]:
# you can compare to correlations too
df.corr(numeric_only=True)

,Ram,Weight,Price,TouchScreen,Ips,Ppi,HDD,SSD
Ram,1.000000,0.389134,0.680519,0.113316,0.202809,0.294927,0.097340,0.599552
Weight,0.389134,1.000000,0.151386,-0.292288,0.023966,-0.319499,0.510876,-0.056985
Price,0.680519,0.151386,1.000000,0.194289,0.279240,0.480687,-0.097361,0.658808
TouchScreen,0.113316,-0.292288,0.194289,1.000000,0.136973,0.452107,-0.205105,0.252142
Ips,0.202809,0.023966,0.279240,0.136973,1.000000,0.288833,-0.090411,0.215197
Ppi,0.294927,-0.319499,0.480687,0.452107,0.288833,1.000000,-0.290774,0.499899
HDD,0.097340,0.510876,-0.097361,-0.205105,-0.090411,-0.290774,1.000000,-0.400625
SSD,0.599552,-0.056985,0.658808,0.252142,0.215197,0.499899,-0.400625,1.000000

In [5]:
df.corr(numeric_only=True)['Price'].sort_values(ascending=False)

Price          1.000000
Ram            0.680519
SSD            0.658808
Ppi            0.480687
Ips            0.279240
TouchScreen    0.194289
Weight         0.151386
HDD           -0.097361
Name: Price, dtype: float64