### VIF-test to test multicollinearity (~redundancy)

In [8]:
# pip install statsmodels
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import pandas as pd

pd.set_option('display.float_format', lambda x: '%.1f' % x) 

import warnings
warnings.filterwarnings("ignore")

# load data
df = pd.read_csv("../laptop_data_cleaned.csv")

In [9]:
# converts nominal variables into binary 

from sklearn.preprocessing import OneHotEncoder
variables = ['Company','TypeName','Cpu_brand','Gpu_brand','Os']
# use encoder
encoder = OneHotEncoder(sparse_output=False, drop="first").set_output(transform="pandas")
one_hot_encoded = encoder.fit_transform(df[variables]).astype(int)
df = pd.concat([df,one_hot_encoded],axis=1).drop(columns=variables)
df.head()

,Ram,Weight,Price,TouchScreen,Ips,Ppi,HDD,SSD,Company_Apple,Company_Asus,...,TypeName_Ultrabook,TypeName_Workstation,Cpu_brand_Intel Core i3,Cpu_brand_Intel Core i5,Cpu_brand_Intel Core i7,Cpu_brand_Other Intel Processor,Gpu_brand_Intel,Gpu_brand_Nvidia,Os_Others,Os_Windows
0,8,1.4,11.2,0,1,227.0,0,128,1,0,...,1,0,0,1,0,0,1,0,0,0
1,8,1.3,10.8,0,0,127.7,0,0,1,0,...,1,0,0,1,0,0,1,0,0,0
2,8,1.9,10.3,0,0,141.2,0,256,0,0,...,0,0,0,1,0,0,1,0,1,0
3,16,1.8,11.8,0,1,220.5,0,512,1,0,...,1,0,0,0,1,0,0,0,0,0
4,8,1.4,11.5,0,1,227.0,0,256,1,0,...,1,0,0,1,0,0,1,0,0,0

In [10]:
# handle these better with your own dataset, here we are simply dropping these
#df = df.drop(['id', 'date', 'zipcode', 'lat', 'long'], axis=1)

# perform X/y -split
# if you  have more than one independent variable, list them all here
# leave out the target variable! (dependent variable)

# this is a nice and common trick => everything EXCEPT target variable => support variable
X = df.drop("Price", axis=1)

# have only the target variable here (dependent variable)
y = df["Price"]


# VIF dataframe 
# VIF = Variance Inflation Factor
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 

# variables with high VIF-value 
# can mean multlicollinearity (variables providing same linear
# relationships in the data, potentially confusing the ML algorithm
# this might be good info when deciding if some variable needs to be removed
vif_data.sort_values(by="VIF", ascending=False)

                            feature                VIF
37                       Os_Windows 1000799917193443.5
7                     Company_Apple 1000799917193443.5
36                        Os_Others 1000799917193443.5
32          Cpu_brand_Intel Core i7                9.6
27                TypeName_Notebook                9.5
31          Cpu_brand_Intel Core i5                8.7
25                  TypeName_Gaming                8.2
33  Cpu_brand_Other Intel Processor                5.1
28               TypeName_Ultrabook                4.8
35                 Gpu_brand_Nvidia                4.4
30          Cpu_brand_Intel Core i3                4.3
34                  Gpu_brand_Intel                4.2
10                     Company_Dell                3.7
2                       TouchScreen                3.5
1                            Weight                3.4
13                       Company_HP                3.2
16                   Company_Lenovo                3.2
6                               SSD                3.0
0                               Ram                2.9
8                      Company_Asus                2.5
4                               Ppi                2.1
17                      Company_MSI                2.1
5                               HDD                2.1
29             TypeName_Workstation                1.9
26                 TypeName_Netbook                1.6
22                  Company_Toshiba                1.6
3                               Ips                1.5
20                    Company_Razer                1.2
19                Company_Microsoft                1.2
18                 Company_Mediacom                1.1
21                  Company_Samsung                1.1
12                   Company_Google                1.1
24                   Company_Xiaomi                1.1
15                       Company_LG                1.1
23                     Company_Vero                1.1
9                     Company_Chuwi                1.1
11                  Company_Fujitsu                1.0
14                   Company_Huawei                1.0