#### Phik-matrix -> Associations

In [10]:
# if phik-matrix not found in pandas, try:
# pip install phik
import phik
import pandas as pd

# load data
df = pd.read_csv("../heart.csv")

# compute phik-matrix values
phik_matrix = df.phik_matrix()

phik_matrix

interval columns not set, guessing: ['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak', 'HeartDisease']

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
Age,1.000000,0.000000,0.247191,0.199907,0.180217,0.235570,0.262350,0.408494,0.256010,0.278651,0.302993,0.360326
Sex,0.000000,1.000000,0.289003,0.000000,0.271783,0.175365,0.033510,0.237847,0.286707,0.151915,0.088767,0.455551
ChestPainType,0.247191,0.289003,1.000000,0.098784,0.197638,0.226491,0.090666,0.351432,0.631005,0.323796,0.298723,0.745661
RestingBP,0.199907,0.000000,0.098784,1.000000,0.000000,0.123913,0.118935,0.116164,0.202694,0.154993,0.176724,0.186177
Cholesterol,0.180217,0.271783,0.197638,0.000000,1.000000,0.421283,0.244923,0.313128,0.134431,0.090337,0.196699,0.430216
FastingBS,0.235570,0.175365,0.226491,0.123913,0.421283,1.000000,0.072456,0.126967,0.074555,0.215462,0.102480,0.401149
RestingECG,0.262350,0.033510,0.090666,0.118935,0.244923,0.072456,1.000000,0.200419,0.058471,0.173870,0.147969,0.059519
MaxHR,0.408494,0.237847,0.351432,0.116164,0.313128,0.126967,0.200419,1.000000,0.529854,0.306548,0.411148,0.527551
ExerciseAngina,0.256010,0.286707,0.631005,0.202694,0.134431,0.074555,0.058471,0.529854,1.000000,0.612048,0.280626,0.697276
Oldpeak,0.278651,0.151915,0.323796,0.154993,0.090337,0.215462,0.173870,0.306548,0.612048,1.000000,0.575568,0.571560
ST_Slope,0.302993,0.088767,0.298723,0.176724,0.196699,0.102480,0.147969,0.411148,0.280626,0.575568,1.000000,0.393847
HeartDisease,0.360326,0.455551,0.745661,0.186177,0.430216,0.401149,0.059519,0.527551,0.697276,0.571560,0.393847,1.000000

In [11]:
# this just converts the value of column to 0 or 1
# factorize in pandas works too, but only one column at a time
from sklearn.preprocessing import LabelEncoder
variables = ['ExerciseAngina']
encoder = LabelEncoder()
df[variables] = df[variables].apply(encoder.fit_transform)

In [12]:
cut_mapper = {'Down': 1, 'Flat': 2,'Up': 3}
df['ST_Slope'] = df['ST_Slope'].map(cut_mapper)

In [13]:
# this makes multiple columns with the variable (Separate for yes/no)
from sklearn.preprocessing import OneHotEncoder
variables = ['Sex', 'ChestPainType', 'RestingECG']

# use encoder
encoder = OneHotEncoder(sparse_output=False).set_output(transform="pandas")
one_hot_encoded = encoder.fit_transform(df[variables]).astype(int)
df = pd.concat([df,one_hot_encoded],axis=1).drop(columns=variables)

In [14]:
df

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Sex_F,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST
0,40,140,289,0,172,0,0.0,3,0,0,1,0,1,0,0,0,1,0
1,49,160,180,0,156,0,1.0,2,1,1,0,0,0,1,0,0,1,0
2,37,130,283,0,98,0,0.0,3,0,0,1,0,1,0,0,0,0,1
3,48,138,214,0,108,1,1.5,2,1,1,0,1,0,0,0,0,1,0
4,54,150,195,0,122,0,0.0,3,0,0,1,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,0,1.2,2,1,0,1,0,0,0,1,0,1,0
914,68,144,193,1,141,0,3.4,2,1,0,1,1,0,0,0,0,1,0
915,57,130,131,0,115,1,1.2,2,1,0,1,1,0,0,0,0,1,0
916,57,130,236,0,174,0,0.0,2,1,1,0,0,1,0,0,1,0,0
917,38,138,175,0,173,0,0.0,3,0,0,1,0,0,1,0,0,1,0

In [15]:
phik_matrix['HeartDisease'].sort_values(ascending=False)

HeartDisease      1.000000
ChestPainType     0.745661
ExerciseAngina    0.697276
Oldpeak           0.571560
MaxHR             0.527551
Sex               0.455551
Cholesterol       0.430216
FastingBS         0.401149
ST_Slope          0.393847
Age               0.360326
RestingBP         0.186177
RestingECG        0.059519
Name: HeartDisease, dtype: float64

In [16]:
# you can compare to correlations too
df.corr(numeric_only=True)

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Sex_F,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST
Age,1.000000,0.254399,-0.095282,0.198039,-0.382045,0.215793,0.258612,-0.268264,0.282039,-0.055750,0.055750,0.166607,-0.218165,-0.011335,0.032042,0.145727,-0.230566,0.136798
RestingBP,0.254399,1.000000,0.100893,0.070193,-0.112135,0.155101,0.164803,-0.075162,0.107589,-0.005133,0.005133,0.048824,-0.046153,-0.041348,0.049855,0.053166,-0.116851,0.090447
Cholesterol,-0.095282,0.100893,1.000000,-0.260974,0.235792,-0.034166,0.050148,0.111471,-0.232741,0.200092,-0.200092,-0.120531,0.150954,-0.006634,0.017365,0.177077,-0.038470,-0.133106
FastingBS,0.198039,0.070193,-0.260974,1.000000,-0.131438,0.060451,0.052698,-0.175774,0.267291,-0.120076,0.120076,0.131176,-0.140514,-0.039249,0.026885,-0.011656,-0.093028,0.127110
MaxHR,-0.382045,-0.112135,0.235792,-0.131438,1.000000,-0.370425,-0.160691,0.343419,-0.400421,0.189186,-0.189186,-0.354963,0.253735,0.134580,0.100025,0.125793,0.023801,-0.157879
ExerciseAngina,0.215793,0.155101,-0.034166,0.060451,-0.370425,1.000000,0.408752,-0.428706,0.494282,-0.190664,0.190664,0.430034,-0.300365,-0.166030,-0.128105,-0.016382,-0.072924,0.107036
Oldpeak,0.258612,0.164803,0.050148,0.052698,-0.160691,0.408752,1.000000,-0.501921,0.403951,-0.105734,0.105734,0.280026,-0.262124,-0.106212,0.032231,0.086794,-0.116719,0.055958
ST_Slope,-0.268264,-0.075162,0.111471,-0.175774,0.343419,-0.428706,-0.501921,1.000000,-0.558771,0.150693,-0.150693,-0.336411,0.332542,0.093376,-0.005235,-0.048901,0.089347,-0.060739
HeartDisease,0.282039,0.107589,-0.232741,0.267291,-0.400421,0.494282,0.403951,-0.558771,1.000000,-0.305445,0.305445,0.516716,-0.401924,-0.212964,-0.054790,0.010670,-0.091580,0.102527
Sex_F,-0.055750,-0.005133,0.200092,-0.120076,0.189186,-0.190664,-0.105734,0.150693,-0.305445,1.000000,-1.000000,-0.183876,0.161522,0.066486,0.004031,0.049518,0.010634,-0.063715
Sex_M,0.055750,0.005133,-0.200092,0.120076,-0.189186,0.190664,0.105734,-0.150693,0.305445,-1.000000,1.000000,0.183876,-0.161522,-0.066486,-0.004031,-0.049518,-0.010634,0.063715
ChestPainType_ASY,0.166607,0.048824,-0.120531,0.131176,-0.354963,0.430034,0.280026,-0.336411,0.516716,-0.183876,0.183876,1.000000,-0.522432,-0.577670,-0.249003,0.002289,-0.063606,0.076438
ChestPainType_ATA,-0.218165,-0.046153,0.150954,-0.140514,0.253735,-0.300365,-0.262124,0.332542,-0.401924,0.161522,-0.161522,-0.522432,1.000000,-0.256767,-0.110679,-0.085791,0.107941,-0.046111
ChestPainType_NAP,-0.011335,-0.041348,-0.006634,-0.039249,0.134580,-0.166030,-0.106212,0.093376,-0.212964,0.066486,-0.066486,-0.577670,-0.256767,1.000000,-0.122381,0.035299,0.005010,-0.042236
ChestPainType_TA,0.032042,0.049855,0.017365,0.026885,0.100025,-0.128105,0.032231,-0.005235,-0.054790,0.004031,-0.004031,-0.249003,-0.110679,-0.122381,1.000000,0.081407,-0.057719,-0.011611
RestingECG_LVH,0.145727,0.053166,0.177077,-0.011656,0.125793,-0.016382,0.086794,-0.048901,0.010670,0.049518,-0.049518,0.002289,-0.085791,0.035299,0.081407,1.000000,-0.623227,-0.248892
RestingECG_Normal,-0.230566,-0.116851,-0.038470,-0.093028,0.023801,-0.072924,-0.116719,0.089347,-0.091580,0.010634,-0.010634,-0.063606,0.107941,0.005010,-0.057719,-0.623227,1.000000,-0.602314
RestingECG_ST,0.136798,0.090447,-0.133106,0.127110,-0.157879,0.107036,0.055958,-0.060739,0.102527,-0.063715,0.063715,0.076438,-0.046111,-0.042236,-0.011611,-0.248892,-0.602314,1.000000

In [17]:
df.corr(numeric_only=True)['HeartDisease'].sort_values(ascending=False)

HeartDisease         1.000000
ChestPainType_ASY    0.516716
ExerciseAngina       0.494282
Oldpeak              0.403951
Sex_M                0.305445
Age                  0.282039
FastingBS            0.267291
RestingBP            0.107589
RestingECG_ST        0.102527
RestingECG_LVH       0.010670
ChestPainType_TA    -0.054790
RestingECG_Normal   -0.091580
ChestPainType_NAP   -0.212964
Cholesterol         -0.232741
Sex_F               -0.305445
MaxHR               -0.400421
ChestPainType_ATA   -0.401924
ST_Slope            -0.558771
Name: HeartDisease, dtype: float64